# Generated by Django 5.1.1 on 2026-09-14 20:10

import django.db.models.deletion
import pgvector.django.vector
from django.db import migrations, models
from pgvector.django import VectorExtension


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        VectorExtension(),
        migrations.CreateModel(
            name='Coffee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('hot', 'Hot'), ('cold', 'Cold'), ('frappe', 'Frappe')], max_length=20)),
                ('milk_type', models.CharField(choices=[('none', 'None'), ('whole', 'Whole Milk'), ('almond', 'Almond Milk'), ('oat', 'Oat Milk'), ('cream', 'Cream')], default='none', max_length=20)),
                ('sweetness', models.CharField(choices=[('none', 'No Sugar'), ('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='none', max_length=20)),
                ('intensity', models.CharField(choices=[('light', 'Light'), ('medium', 'Medium'), ('strong', 'Strong')], default='medium', max_length=20)),
                ('ingredients', models.JSONField(default=list)),
                ('image_url', models.CharField(blank=True, default='', max_length=255)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('embedding', pgvector.django.vector.VectorField(blank=True, dimensions=384, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Coffee',
                'verbose_name_plural': 'Coffees',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CoffeeOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('coffee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='coffees.coffee')),
            ],
            options={
                'verbose_name': 'Coffee Order',
                'verbose_name_plural': 'Coffee Orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SearchLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_text', models.TextField()),
                ('similarity_score', models.FloatField(default=0.0)),
                ('was_selected', models.BooleanField(default=False)),
                ('llm_response', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recommended_coffee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='search_logs', to='coffees.coffee')),
            ],
            options={
                'verbose_name': 'Search Log',
                'verbose_name_plural': 'Search Logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
